#!/usr/bin/env ruby
begin
	require 'rubygems'
rescue LoadError
end  

require 'clap'

%w{crontest crontab_file crontab_helper}.each { |f| require File.expand_path("lib/#{f}", File.dirname(__FILE__)) }

opts = {}

args = Clap.run ARGV,
   "--no-backup" => lambda { opts[:backup] = false },
   "-n" => lambda { opts[:backup] = false },
   "-v" => lambda { opts[:verbose] = true }
  
command = args.first or raise "no command specified"
 
Crontest.run(command, opts)