#!/usr/bin/env ruby
begin
	require 'rubygems'
rescue LoadError
end  

require 'clap'

require 'lib/crontest'
require 'lib/crontab_helper'
require 'lib/crontab_file'

opts = {}

args = Clap.run ARGV,
   "--no-backup" => lambda { opts[:backup] = false },
   "-n" => lambda { opts[:backup] = false },
   "-v" => lambda { opts[:verbose] = true }
  
command = args.first or raise "no command specified"
 
Crontest.run(command, opts)