#+COMMENT: -*- org -*-
#+TITLE:     crontest
#+AUTHOR:    Ari Russo
#+DATE:      2010-10-13 Wed
#+TEXT: ruby library/ command line tool for testing cron jobs
#+KEYWORDS: cron, crontest, cron-test, crontab, linux, unix, test, tasks, jobs 
#+LANGUAGE:  en
#+LINK_HOME: http://github.com/arirusso/crontest

* Summary

Ruby lib/command line tool for testing cron jobs

* Description

Execute an (almost) immediate and transient cron job from the command line

* Requires

	- [[http://github.com/soveran/clap][clap]]  
	
* Usage

to run crontest from the command line:

	: ./crontest 'echo hello! > MY_CRON_TEST.txt' &
	
to use the gem

	: require 'crontest'
	: Crontest.run("echo hello! > MY_CRON_TEST.txt")
	
these will both run =echo hello! > MY_CRON_TEST.txt= as a cron job.  it can take up to a minute to run as cron's timing resolution is one minute.

crontest will create a backup file of your current crontab (cron-backup-[timestamp]) in the directory where directory you run it. 

Options:

pass in options from the command line or Crontest.run(command, options)

: --no-backup 
: -n
: :backup => false 
no backup file

: -v
: verbose => true
verbose output 

* Caution

I highly encourage you to keep a separate backup of your crontab before trying this tool as it is brand new and relatively untested.
