#+COMMENT: -*- org -*-
#+TITLE:     crontest
#+AUTHOR:    Ari Russo
#+DATE:      2010-10-13 Wed
#+TEXT: Command line tool for testing cron tasks
#+KEYWORDS: cron, crontest, cron-test, crontab, linux, unix, test, tasks 
#+LANGUAGE:  en
#+LINK_HOME: http://github.com/arirusso/crontest

* Summary

Command line tool for testing cron tasks

* Description

Execute a command as though it is being run by the current user's crontab   

* Installation

: sudo gem install crontest
	
* Usage

	: crontest 'echo hello! > MY_CRON_TEST.txt' &
	
this command will run =crontest 'echo hello! > MY_CRON_TEST.txt' &= in the environment that cron jobs will run for the current user.  it can take up to a minute to run as crontab's timing resolution is one minute.

crontest will create a backup file of your current crontab (cron-backup-[timestamp]) in the directory where directory you run it. adding the parameter =--no-backup= or =-n= will force it to run without creating that file

use =-v= for verbose output

* Caution

I highly encourage you to keep a separate backup of your crontab before trying this tool as it is brand new and relatively untested.